### ISSUE TITLE
Receiver daemon is not considered

### ISSUE THREAD

**Issue by mohierf** [david-guenault/shinken-packs#3]
In templates.cfg, missing receiver in _shinken_daemons list ...

Anyway ... check_shinken2.py does not take care of receiver and must also be fixed for this.

**Comment by david-guenault** [comment]
yup saw this some days ago. And there was much more thant that. Curently fixing it. 

Thx for report

**Comment by mohierf** [comment]
Should not be better to use a tag as "shinken2" instead of "arbiter2" and an aggregation "shinken2" for the services ?

Before my fix :
![image](https://cloud.githubusercontent.com/assets/2932687/7553483/b2fcd790-f6fb-11e4-8fb5-0f752b9a2b28.png)

After a small fix : 

![image](https://cloud.githubusercontent.com/assets/2932687/7553515/feb98628-f6fc-11e4-8be6-2b4595cbcf02.png)

**Comment by david-guenault** [comment]
also right. I'm curently fixing some issues since the tls integration (now plugin support ss/tls)

**Comment by david-guenault** [comment]
Can you submit a pr for that ?

**Comment by mohierf** [comment]
I tried so ... but I cannot !

I cloned your repo and created a local branch, then I commited my modifications and built a PR for my new branch. But I cannot : 

```
git push --set-upstream origin Shinken2-aggregation
remote: Permission to david-guenault/shinken-packs.git denied to 85268319e784cef9fe2c742e719c48adaaf36a3a.
fatal: unable to access 'https://github.com/david-guenault/shinken-packs.git/': The requested URL returned error: 403
```

**Comment by david-guenault** [comment]
You have to push to tour repo ( fork) then use github to sublit pr. It's
that simple

**Comment by mohierf** [comment]
Thanks ... I tried to PR directly into your repo :/P
